version: '3.8'

services:
  demo-actix-web:
    container_name: demo-actix-web
    build:
      context: .
      # args:
      #   DATABASE_URL: postgres://postgres:postgres@db:3306/postgres
    ports:
    - "5000:8080"
    # depends_on:
    #   - db      
    environment:
      - RUST_LOG=debug
      - TZ=America/Bogota
  
#   db:
#     container_name: db
#     image: postgres:13.3-apine
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: postgres
#     ports:
#       - '5432:5432'
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: {}